apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-att
  labels:
    app.kubernetes.io/name: helloworld-att
    app.kubernetes.io/instance: helloworld-att
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: helloworld-att
      app.kubernetes.io/instance: helloworld-att
  template:
    metadata:
      labels:
        app.kubernetes.io/name: helloworld-att
        app.kubernetes.io/instance: helloworld-att
    spec:
      containers:
        - name: helloworld-att
          image: asia.gcr.io-poc-innovation-iot/kustomize-helloworld
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            timeoutSeconds: 10
            initialDelaySeconds: 10
          resources: 
            limits: 
              cpu: 64m
              memory: 32Mi
            requests: 
              cpu: 32m
              memory: 6